import { AutocompleteFilter } from 'getaddress-api';
import { OutputFields } from "./OutputFields";
export declare class Options {
    static show_all_for_postcode_defaut: boolean;
    static show_all_for_postcode_text_default: string;
    id_prefix?: string;
    css_prefix?: string;
    output_fields?: Partial<OutputFields>;
    delay?: number;
    minimum_characters?: number;
    clear_list_on_select?: boolean;
    select_on_focus?: boolean | undefined;
    show_all_for_postcode?: boolean | undefined;
    show_all_for_postcode_text?: string | undefined;
    alt_autocomplete_url?: string;
    alt_get_url?: string;
    input_class_names?: string[];
    input_show_class_names?: string[];
    list_class_names?: string[];
    container_class_names?: string[];
    suggestion_class_names?: string[];
    suggestion_focused_class_names?: string[];
    suggestion_show_all_class_names?: string[];
    list_show_all_class_names?: string[];
    container_focused_class_names?: string[];
    highlight_suggestion?: boolean | undefined;
    highlight_suggestion_start_tag?: string | undefined;
    highlight_suggestion_end_tag?: string | undefined;
    list_width?: string;
    suggestion_count?: number | undefined;
    auto_calc_list_height?: boolean | undefined;
    suggestion_template?: string | undefined;
    filter?: Partial<AutocompleteFilter>;
    bind_output_fields?: boolean | undefined;
    input_focus_on_select?: boolean | undefined;
    debug?: boolean | undefined;
    enable_get?: boolean | undefined;
    set_default_output_field_names?: boolean | undefined;
    remember_last_search?: boolean | undefined;
    constructor(options?: Partial<Options>);
}
